### ISSUE TITLE
migrating to humble from foxy

### ISSUE THREAD

**Issue by ryanpennings** [Factor-Robotics/odrive_ros2_control#20]
I'm trying to move over to humble, and I've managed to get all the return types fixed (as seen in #11) - I made 2 check functions, not sure that's the best way to go about it..

However, now I'm getting this error:
![image](https://user-images.githubusercontent.com/20721614/179461072-dfc9ff8a-5524-4c20-b31c-dbf11ef0a732.png)

https://github.com/MSDRobotics/odrive_ros2_control/tree/devel/odrive_hardware_interface

Anyone have any ideas?

**Comment by borongyuan** [comment]
I just installed ROS Humble recently. We plan to continue updating this project from next month. Looking forward to your contributions :)

**Comment by ryanpennings** [comment]
Thanks, I'm hoping to implement CAN after this too.

**Comment by ryanpennings** [comment]
I was able to fix it by adding `const rclcpp::Time & time, const rclcpp::Duration & period` to the read and write functions, as seen in this example:
https://github.com/ros-controls/ros2_control_demos/blob/master/ros2_control_demo_hardware/include/ros2_control_demo_hardware/diffbot_system.hpp

**Comment by maxpolzin** [comment]
Nice @ryanpennings. Does that mean your branch is working for humble?

**Comment by ryanpennings** [comment]
> Nice @ryanpennings. Does that mean your branch is working for humble? 

It builds, but I haven't tested it yet.
