### ISSUE TITLE
运行指令电机不动

### ISSUE THREAD

**Issue by shipeng-liu** [Factor-Robotics/odrive_ros2_control#4]
电机初始化运行launch文件正常，在odrivetool模式下，可以使用速度控制，但是在ros2模式下， 运行命令
![image](https://user-images.githubusercontent.com/45789865/142503296-508ab556-baef-42d5-aa23-7d1404aa231e.png)
电机无反应

**Comment by shipeng-liu** [comment]
试了一下10，转了，可能是1rad/s太小了

**Comment by borongyuan** [comment]
对于低速控制，建议配置和启用ODrive的抗齿槽功能，再进行PID调参

**Comment by shipeng-liu** [comment]
感谢，这个是odrive本身的问题吧， 还有就是现在使用odrive ros control 控制时每次电机断电后，需要重新连odrivetool calibrate calibrate， 这个命令可以通过ros发消息来控制嘛

**Comment by borongyuan** [comment]
电机并不需要每次重新校准，应在校准后将对应的pre_calibrated设为True。请配置正确的启动程序，上电会自动执行编码器找零或offset校准，取决于使用的编码器。即便需要每次上电校准电机，也可以配置对应的启动程序。我们认为odrive的启动程序已处理了这些流程，因此不在ROS驱动里做对应接口。
